# Schema

SCHEMA_TITLE_MIN_LENGTH = 4  # test
SCHEMA_TITLE_MAX_LENGTH = 128
SCHEMA_URL_MAX_LENGTH = 32

# Rows

COLUMN_TYPE_LENGTH = 1  # row type is 1 letter for DB to make search easier
COLUMN_SEPARATOR_LENGTH = 1
COLUMN_STRING_QUOTES_LENGTH = 1
COLUMN_HEADER_MIN_LENGTH = 4
COLUMN_HEADER_MAX_LENGTH = 64
