# Generated by Django 4.1.7 on 2023-03-01 11:02

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schema",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=128, verbose_name="Schema title"),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        max_length=32,
                        populate_from="title",
                        unique_with=("user",),
                    ),
                ),
                (
                    "edited_at",
                    models.DateTimeField(auto_now=True, verbose_name="Edited"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schema",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Schema",
                "verbose_name_plural": "Schemas",
                "db_table": "user_schemas",
                "ordering": ["title", "-edited_at"],
                "unique_together": {("title", "user")},
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "header",
                    models.CharField(max_length=64, verbose_name="Column header"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("n", "Full name"),
                            ("j", "Job"),
                            ("e", "Email"),
                            ("d", "Domain name"),
                            ("p", "Phone number"),
                            ("c", "Company name"),
                            ("t", "Text"),
                            ("i", "Integer"),
                            ("a", "Address"),
                            ("d", "Date"),
                        ],
                        max_length=1,
                        verbose_name="Record data type",
                    ),
                ),
                ("data", models.TextField(verbose_name="Record data")),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record",
                        to="fake_schemas_generation.schema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Record data",
                "verbose_name_plural": "Records data",
                "db_table": "schema_records",
                "ordering": ["schema", "order"],
                "unique_together": {("header", "schema", "order")},
            },
        ),
    ]
