# Generated by Django 4.1.7 on 2023-03-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fake_schemas_generation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schema",
            name="quotes",
            field=models.CharField(
                choices=[('"', '"'), ("'", "'")], default='"', max_length=1
            ),
        ),
        migrations.AddField(
            model_name="schema",
            name="separator",
            field=models.CharField(
                choices=[(",", ","), (";", ";")], default=",", max_length=1
            ),
        ),
    ]
