# Generated by Django 4.1.7 on 2023-03-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fake_schemas_generation", "0002_schema_quotes_schema_separator"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="end_integer",
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="sentences",
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="start_integer",
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="type",
            field=models.CharField(
                choices=[
                    ("df", "Column data type"),
                    ("fn", "Full name"),
                    ("j", "Job"),
                    ("e", "Email"),
                    ("dn", "Domain name"),
                    ("pn", "Phone number"),
                    ("cn", "Company name"),
                    ("t", "Text"),
                    ("i", "Integer"),
                    ("a", "Address"),
                    ("d", "Date"),
                ],
                default="",
                max_length=2,
                verbose_name="Record data type",
            ),
        ),
        migrations.AlterField(
            model_name="schema",
            name="quotes",
            field=models.CharField(
                choices=[('"', 'Double quote (")'), ("'", "Single quote (')")],
                default='"',
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="schema",
            name="separator",
            field=models.CharField(
                choices=[(",", "Comma (,)"), (";", "Semicolon (;)")],
                default=",",
                max_length=1,
            ),
        ),
    ]
