# Generated by Django 4.1.7 on 2023-03-01 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "fake_schemas_generation",
            "0003_record_end_integer_record_sentences_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="data",
        ),
    ]
