# Generated by Django 4.1.7 on 2023-03-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fake_schemas_generation", "0004_remove_record_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="end_integer",
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="sentences",
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="start_integer",
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
