# Generated by Django 4.1.7 on 2023-03-02 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "fake_schemas_generation",
            "0005_alter_record_end_integer_alter_record_sentences_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="record",
            unique_together={("schema", "order")},
        ),
    ]
