# Generated by Django 4.1.7 on 2023-03-02 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fake_schemas_generation", "0006_alter_record_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schema",
            options={
                "ordering": ["title", "edited_at"],
                "verbose_name": "Schema",
                "verbose_name_plural": "Schemas",
            },
        ),
    ]
