# Generated by Django 4.1.7 on 2023-03-02 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fake_schemas_generation", "0007_alter_schema_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schema",
            options={
                "ordering": ["-edited_at", "title"],
                "verbose_name": "Schema",
                "verbose_name_plural": "Schemas",
            },
        ),
    ]
