# Generated by Django 4.1.7 on 2023-03-02 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fake_schemas_generation", "0009_alter_record_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="record",
            unique_together={("schema", "order")},
        ),
    ]
