# Generated by Django 4.1.7 on 2023-03-02 12:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("fake_schemas_generation", "0010_alter_record_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "header",
                    models.CharField(max_length=64, verbose_name="Column header"),
                ),
                (
                    "start_integer",
                    models.PositiveSmallIntegerField(
                        blank=True, default=None, null=True
                    ),
                ),
                (
                    "end_integer",
                    models.PositiveSmallIntegerField(
                        blank=True, default=None, null=True
                    ),
                ),
                (
                    "sentences",
                    models.PositiveSmallIntegerField(
                        blank=True, default=None, null=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("df", "Column data type"),
                            ("fn", "Full name"),
                            ("j", "Job"),
                            ("e", "Email"),
                            ("dn", "Domain name"),
                            ("pn", "Phone number"),
                            ("cn", "Company name"),
                            ("t", "Text"),
                            ("i", "Integer"),
                            ("a", "Address"),
                            ("d", "Date"),
                        ],
                        default="",
                        max_length=2,
                        verbose_name="Column data type",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column",
                        to="fake_schemas_generation.schema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Record data",
                "verbose_name_plural": "Records data",
                "db_table": "schema_columns",
                "ordering": ["schema", "order"],
                "unique_together": {("schema", "order")},
            },
        ),
        migrations.DeleteModel(
            name="Record",
        ),
    ]
